spring.application.name=${artifactId}

server.port=8000
# server.servlet.contextPath=/api

# --- OPENAPI ---
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# --- DATABASE ---#[[
spring.datasource.url=jdbc:${DB_PROVIDER}://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=${DB_PLATFORM}
spring.jpa.properties.hibernate.format_sql=true

# --- ENVERS ---
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_audit
spring.jpa.properties.org.hibernate.envers.revision_field_name=revision_id
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=revision_type
spring.jpa.properties.hibernate.integration.envers.enabled=true

# --- OAUTH ---
# NOTE: Remove if not using an external IDP
spring.security.oauth2.resourceserver.jwt.issuer-uri=${IDP_ISS_URI}]]#

